const NCPDP_D0_Config = {
    "1_cardholderFirstName":  {"displayOrder" : 1, "displayName": "Cardholder First Name","location": {"segment": "AM04", "dataElementId": "CC"}, "deidentify" : true, "defaultValue": "CARDHOLDER FIRSTNAME"},
    "2_cardholderLastName":   {"displayOrder" : 2, "displayName": "Cardholder Last Name","location": {"segment": "AM04", "dataElementId": "CD"}, "deidentify" : true, "defaultValue": "CARDHOLDER LASTNAME"},
    "3_patientFirstName":     {"displayOrder" : 3, "displayName": "Patient First Name","location": {"segment": "AM01", "dataElementId": "CA"}, "deidentify" : true, "defaultValue": "PATIENT FIRSTNAME"},
    "4_patientLastName":      {"displayOrder" : 4, "displayName": "Patient Last Name","location": {"segment": "AM01", "dataElementId": "CB"}, "deidentify" : true, "defaultValue": "PATIENT LASTNAME"},
    "5_prescriberLastName":   {"displayOrder" : 5, "displayName": "Prescriber Last Name","location": {"segment": "AM03", "dataElementId": "DR"}, "deidentify" : true, "defaultValue": "PRESCRIBER LASTNAME"},
    "6_prescriberFirstName":  {"displayOrder" : 6, "displayName": "Prescriber First Name","location": {"segment": "AM03", "dataElementId": "2J"}, "deidentify" : true, "defaultValue": "PRESCRIBER FIRSTNAME"},
    "7_primaryCareProviderLastName":  {"displayOrder" : 7, "displayName": "Primary Care Provider Last Name","location": {"segment": "AM03", "dataElementId": "4E"}, "deidentify" : true, "defaultValue": "PCP LASTNAME"},
    "8_employerName":         {"displayOrder" : 8, "displayName": "Employer Name","location": {"segment": "AM06", "dataElementId": "CF"}, "deidentify" : true, "defaultValue": "DEID EMPLOYER INC."},
    "9_employerContactName":  {"displayOrder" : 9, "displayName": "Employer Contact Name","location": {"segment": "AM06", "dataElementId": "CL"}, "deidentify" : true, "defaultValue": "JOHN DOE"},
    "10_payToName":            {"displayOrder" : 10, "displayName": "Pay To Name","location": {"segment": "AM06", "dataElementId": "TU"}, "deidentify" : true, "defaultValue": "PAY TO NAME"},
    "11_facilityName":         {"displayOrder" : 11, "displayName": "Facility Name","location": {"segment": "AM15", "dataElementId": "5J"}, "deidentify" : true, "defaultValue": "MEDICAL OFFICE LLC"},
    "12_prescriptionNumber":{"displayOrder" : 12, "displayName": "Prescription Number","location": {"segment": "AM07", "dataElementId": "D2"}, "deidentify" : true, "defaultValue": "5600000000001"},
    "13_medicaidIdNumber": {"displayOrder" : 13, "displayName": "Medicaid ID Number","location": {"segment": "AM04", "dataElementId": "N5"}, "deidentify" : true, "defaultValue": "MEDICAID NUMBER"},
    "14_groupId":          {"displayOrder" : 14, "displayName": "Group ID","location": {"segment": "AM04", "dataElementId": "C1"}, "deidentify" : true, "defaultValue": "GROUPD ID"},
    "15_cardholderId":     {"displayOrder" : 15, "displayName": "Cardholder ID", "location": {"segment": "AM04", "dataElementId": "C2"}, "deidentify" : true, "defaultValue": "CARDHOLDER ID"},
    "16_medigapId":        {"displayOrder" : 16, "displayName": "Medigap ID","location": {"segment": "AM04", "dataElementId": "2A"}, "deidentify" : true, "defaultValue": "MEDIGAP ID"},
    "17_planId":           {"displayOrder" : 17, "displayName": "Plan ID","location": {"segment": "AM04", "dataElementId": "FO"}, "deidentify" : true, "defaultValue": "PLAN ID"},
    "18_patienId":         {"displayOrder" : 18, "displayName": "Patient ID","location": {"segment": "AM01", "dataElementId": "CY"}, "deidentify" : true, "defaultValue": "PATIENT ID"},
    "19_employerId":       {"displayOrder" : 19, "displayName": "Employer ID","location": {"segment": "AM01", "dataElementId": "CZ"}, "deidentify" : true, "defaultValue": "EMPLOYER ID"},
    "20_providerId":       {"displayOrder" : 20, "displayName": "Provider ID","location": {"segment": "AM02", "dataElementId": "E9"}, "deidentify" : true, "defaultValue": "PROVIDER ID"},
    "21_prescriberId":     {"displayOrder" : 21, "displayName": "Prescriber ID","location": {"segment": "AM03", "dataElementId": "E9"}, "deidentify" : true, "defaultValue": "PRESCRIBER ID"},
    "22_primaryCareProviderId": {"displayOrder" : 22, "displayName": "Primary Care Provider ID","location": {"segment": "AM03", "dataElementId": "DL"}, "deidentify" : true, "defaultValue": "PCP ID"},
    "23_otherPayerId":     {"displayOrder" : 23, "displayName": "Other Payer ID","location": {"segment": "AM05", "dataElementId": "7C"}, "deidentify" : true, "defaultValue": "OTHER PAYER ID"},
    "24_carrierId":        {"displayOrder" : 24, "displayName": "Carrier ID","location": {"segment": "AM06", "dataElementId": "CR"}, "deidentify" : true, "defaultValue": "CARRIER ID"},
    "25_claimId":          {"displayOrder" : 25, "displayName": "Claim ID","location": {"segment": "AM06", "dataElementId": "DZ"}, "deidentify" : true, "defaultValue": "CLAIM ID"},
    "26_payToId":          {"displayOrder" : 26, "displayName": "Pay To ID","location": {"segment": "AM06", "dataElementId": "TT"}, "deidentify" : true, "defaultValue": "PAY TO ID"},
    "27_facilityId":       {"displayOrder" : 27, "displayName": "Facility ID","location": {"segment": "AM15", "dataElementId": "8C"}, "deidentify" : true, "defaultValue": "FACILITY ID"},
    "28_patientStreetAddress":{"displayOrder" : 28, "displayName": "Patient Street Address","location": {"segment": "AM01", "dataElementId": "CM"}, "deidentify" : true, "defaultValue": "1234 PATIENT STREET"},
    "29_patientCity":      {"displayOrder" : 29, "displayName": "Patient City","location": {"segment": "AM01", "dataElementId": "CN"}, "deidentify" : true, "defaultValue": "PATIENT CITY"},
    "30_patientZip":       {"displayOrder" : 30, "displayName": "Patient Zip","location": {"segment": "AM01", "dataElementId": "CP"}, "deidentify" : true, "defaultValue": "00300"},
    "31_patientPhone":     {"displayOrder" : 31, "displayName": "Patient Phone","location": {"segment": "AM01", "dataElementId": "CQ"}, "deidentify" : true, "defaultValue": "5555555555"},
    "32_patientEmail":     {"displayOrder" : 32, "displayName": "Patient Email","location": {"segment": "AM01", "dataElementId": "HN"}, "deidentify" : true, "defaultValue": "patient@deid.da"},
    "33_prescriberPhone":  {"displayOrder" : 33, "displayName": "Prescriber Phone","location": {"segment": "AM03", "dataElementId": "PM"}, "deidentify" : true, "defaultValue": "7777777777"},
    "34_prescriberStreetAddress":{"displayOrder" : 34, "displayName": "Prescriber Street Address","location": {"segment": "AM03", "dataElementId": "2K"}, "deidentify" : true, "defaultValue": "567 PRESCRIBER STREET"},
    "35_prescriberCity":   {"displayOrder" : 35, "displayName": "Prescriber City","location": {"segment": "AM03", "dataElementId": "2M"}, "deidentify" : true, "defaultValue": "PRESCRIBER CITY"},
    "36_prescriberZip":    {"displayOrder" : 36, "displayName": "Prescriber Zip","location": {"segment": "AM03", "dataElementId": "2P"}, "deidentify" : true, "defaultValue": "00489"},
    "37_employerStreetAddress":{"displayOrder" : 37, "displayName": "Employer Street Address","location": {"segment": "AM06", "dataElementId": "CG"}, "deidentify" : true, "defaultValue": "444 EMPLOYER STREET"},
    "38_employerCity":     {"displayOrder" : 38, "displayName": "Employer City","location": {"segment": "AM06", "dataElementId": "CH"}, "deidentify" : true, "defaultValue": "EMPLOYER CITY"},
    "39_employerZip":      {"displayOrder" : 39, "displayName": "Employer Zip","location": {"segment": "AM06", "dataElementId": "CJ"}, "deidentify" : true, "defaultValue": "EMPLOYER ZIP"},
    "40_employerPhone":    {"displayOrder" : 40, "displayName": "Employer Phone","location": {"segment": "AM06", "dataElementId": "CK"}, "deidentify" : true, "defaultValue": "6666666666"},
    "41_payToStreetAddress":{"displayOrder" : 41, "displayName": "Pay To Street Address","location": {"segment": "AM06", "dataElementId": "TV"}, "deidentify" : true, "defaultValue": "897 PAY TO STREET"},
    "42_payToCity":        {"displayOrder" : 42, "displayName": "Pay To City","location": {"segment": "AM06", "dataElementId": "TW"}, "deidentify" : true, "defaultValue": "PAY TO CITY"},
    "43_payToZip":         {"displayOrder" : 43, "displayName": "Pay To Zip","location": {"segment": "AM06", "dataElementId": "TY"}, "deidentify" : true, "defaultValue": "00111"},   
    "44_facilityStreetAddress":{"displayOrder" : 44, "displayName": "Facility Street Address","location": {"segment": "AM15", "dataElementId": "3U"}, "deidentify" : true, "defaultValue": "987 FACILITY STREET"},
    "45_facilityCity":     {"displayOrder" : 45, "displayName": "Facility City","location": {"segment": "AM15", "dataElementId": "5J"}, "deidentify" : true, "defaultValue": "FACILITY CITY"},
    "46_facilityZip":      {"displayOrder" : 46, "displayName": "Facility Zip","location": {"segment": "AM15", "dataElementId": "6D"}, "deidentify" : true, "defaultValue": "00477"},
    "47_BIN":              {"displayOrder" : 47, "displayName": "BIN Number","location": {"segment": "HEADER", "dataElementId": "A1"}, "deidentify" : true, "defaultValue": "7777"},
    "48_PCN":              {"displayOrder" : 48, "displayName": "Processor Control Number","location": {"segment": "HEADER", "dataElementId": "A4"}, "deidentify" : true, "defaultValue": "PCN"},
    "49_serviceProviderId":{"displayOrder" : 49, "displayName": "Service Provider ID","location": {"segment": "HEADER", "dataElementId": "B1"}, "deidentify" : true, "defaultValue": "9090909090"},
    "51_softwareVendor":   {"displayOrder" : 50, "displayName": "Software Vendor","location": {"segment": "HEADER", "dataElementId": "AK"}, "deidentify" : true, "defaultValue": "CHELI SOFT"},
    "51_groupId":          {"displayOrder" : 51, "displayName": "Group ID","location": {"segment": "AM25", "dataElementId": "C1"}, "deidentify" : true, "defaultValue": "GROUP ID"},
    "52_planId":          {"displayOrder" : 52, "displayName": "Plan ID","location": {"segment": "AM25", "dataElementId": "FO"}, "deidentify" : true, "defaultValue": "PLAN ID"},
    "53_payerId":         {"displayOrder" : 53, "displayName": "Payer ID","location": {"segment": "AM25", "dataElementId": "J8"}, "deidentify" : true, "defaultValue": "PAYER ID"},
    "54_cardholderId":    {"displayOrder" : 54, "displayName": "CardholderID","location": {"segment": "AM25", "dataElementId": "C2"}, "deidentify" : true, "defaultValue": "CARDHOLDER ID"},
    "55_patientFirstName":{"displayOrder" : 55, "displayName": "Patient First Name","location": {"segment": "AM29", "dataElementId": "CA"}, "deidentify" : true, "defaultValue": "PATIENT FIRSTNAME"},
    "56_patientLastName": {"displayOrder" : 56, "displayName": "Patient Last Name","location": {"segment": "AM29", "dataElementId": "CB"}, "deidentify" : true, "defaultValue": "PATIENT LASTNAME"},
    "57_dateOfBirth":     {"displayOrder" : 57, "displayName": "Date Of Birth","location": {"segment": "AM01", "dataElementId": "C4"}, "deidentify" : true, "defaultValue": "19000101"},
    "58_dateOfBirth":     {"displayOrder" : 58, "displayName": "Date Of Birth","location": {"segment": "AM29", "dataElementId": "C4"}, "deidentify" : true, "defaultValue": "19000101"},
    "59_helpDeskPhone":   {"displayOrder" : 59, "displayName": "Help Desk Phone","location": {"segment": "AM21", "dataElementId": "8F"}, "deidentify" : true, "defaultValue": "5555555555"},
    "60_prescriptionNumber":{"displayOrder" : 60, "displayName": "Prescription Number","location": {"segment": "AM22", "dataElementId": "D2"}, "deidentify" : true, "defaultValue": "5600000000001"},
    "61_otherPayerId":    {"displayOrder" : 61, "displayName": "Other Payer ID","location": {"segment": "AM24", "dataElementId": "7C"}, "deidentify" : true, "defaultValue": "OTHER PAYER ID"},    
    "62_otherPayerCardholderId":    {"displayOrder" : 62, "displayName": "Other Payer Cardholder ID","location": {"segment": "AM24", "dataElementId": "NU"}, "deidentify" : true, "defaultValue": "OTHER CARHHOLDER ID"},    
    "63_otherPayerGroupId": {"displayOrder" : 63, "displayName": "Other Payer Group ID","location": {"segment": "AM24", "dataElementId": "MJ"}, "deidentify" : true, "defaultValue": "OTHER PAYER GROUP ID"},    
    "64_otherPayerHelpDeskPhone":   {"displayOrder" : 64, "displayName": "Other Payer Help Desk Phone","location": {"segment": "AM24", "dataElementId": "UB"}, "deidentify" : true, "defaultValue": "7777777777"},
    "65_authorizationNumber" : {"displayOrder" : 65, "displayName": "Authorization Number","location": {"segment": "AM21", "dataElementId": "F3"}, "deidentify" : true, "defaultValue": "AUTHORIZATION NUMBER"},
}
export default NCPDP_D0_Config;