const SCRIPTTransctionNames = {
    RxRenewalRequest: "Prescription Renewal Request",
    RxRenewalResponse: "Prescription Renewal Response",
    NewRx: "New Prescription",
    RxChangeRequest: "Prescription Change Request",
    RxChangeResponse: "Prescription Change Response",
    RxFill: "Prescription Has been Dispensed",
    CancelRx: "Cancel a Prescription Request",
    CancelRxResponse: "Cancel Prescription Response",
    GetMessage: "Get Message",
    PasswordChange: "",
    Verify: "Verify",
    Error: "Error",
    RxHistoryRequest: "Prescriptin History Request",
    RxHistoryResponse: "Prescription History Response",
    Census: "",
    Resupply: "",
    Recertification: "",
    DrugAdministration: "",
    MTMServiceRequest: "MTM Service Request",
    MTMServiceResponse: "MTM Service Response",
    NewRxRequest: "New Prescription Request",
    NewRxResponseDenied: "New Prescription Response Denied",
    ClinicalInfoRequest: "Clinical Information Request",
    ClinicalInfoResponse: "Clinical Information Response",
    PAInitiationRequest: "Prior Authorization Initiation Request",
    PAInitiationResponse: "Prior Authorization Intiation Response",
    PARequest: "Prior Authorization Request",
    PAResponse: "Prior Authorization Response",
    PAAppealRequest: "Prior Authorization Appeal Request",
    PAAppealResponse: "Prior Authorization Appeal Response",
    PACancelRequest: "Prior Authorization Cancel Request",
    PACancelResponse: "Prior Authorization Response",
    CFInventoryList: "Central Fill Inventory List",
    CFProductInquiry: "Central Fill Product Inquiry",
    CFProductInquiryResponse: "Central Fill Product Inquiry Response",
    CFRxOrderRequest: "Central Fill Prescription Order Request",
    CFRxOrderCompletion: "Central Fill Prescription Order Completion",
    CFRxOrderCancel: "Central Fill Prescription Order Cancel",
    CFManifest: "Central Fill Manifest",
    RxTransferRequest: "Prescription Transfer Request",
    RxTransferResponse: "Prescription Transfer Response",
    RxTransferConfirm: "Prescription Transfer Confirmation",
    RxFillIndicatorChange: "Prescription Fill Indicator Change",
    REMSInitiationRequest: "REMS Initiation Reqeust",
    REMSInitiationResponse: "REMS Initiaion Response",
    REMSRequest: "REMS Request",
    REMSResponse: "REMS Response",
    Status: "Status",
    RefillRequest: "Prescription Refill Request",
    RefillResponse: "Prescription Refill Response",
}

export default SCRIPTTransctionNames;