const types = {
    SET_CONFIG_PARAMETERS: "SET_CONFIG_PARAMETERS",
    STATE_CHANGED: "STATE_CHANGED",
    DEFAULT_VALUE_CHANGED: "DEFAULT_VALUE_CHANGED",
    USER_PREFS_DEFINED: "USER_PREFS_DEFINED"
}

export default types;